In [1]:
import pandas as pd
import os

#운동 부위에 따른 운동 부위 전처리
filename = 'Shoulders' #운동 부위 : abs, arms, back, butt, chest, Legs-Thighs, Legs-Calves and Shins, Full-body, Shoulders

file_list = os.listdir('img2/'+filename)
index = []
training_name = []
training_index = []

for i in range(len(file_list)) :
    #각 운동 부위 운동 이미지, 순서 추출
    training_index.append(file_list[i][file_list[i].find('-',len(file_list[i])-7)+1:].split('.')[0])
    training_name.append(file_list[i][:file_list[i].find('-',len(file_list[i])-7)])
    index.append(i+1)


file = pd.DataFrame({'index':index,'training_name':training_name,'training_index':training_index})

In [2]:
file

     index            training_name training_index
0        1          Barbell Jammers              1
1        2          Barbell Jammers              2
2        3          Barbell Jammers              3
3        4          Barbell Jammers              4
4        5          Barbell Jammers              5
..     ...                      ...            ...
204    205     TRX ® Suspended Pike              2
205    206     TRX ® Suspended Pike              3
206    207  TRX ® Suspended Push-up              1
207    208  TRX ® Suspended Push-up              2
208    209                  V-raise              1

[209 rows x 3 columns]

In [4]:
#파일 저장
file.to_csv(filename+'_img_info.csv', index=False, encoding='cp949')

In [5]:
#크롤링 데이터 통합 및 전처리 준비
df = pd.read_csv('list.csv')
df

     TRAINING_INDEX               IMG_NAME
0                 1            Front Squat
1                 2            Front Squat
2                 3            Front Squat
3                 1             Hang Clean
4                 2             Hang Clean
..              ...                    ...
201               2  Seated Shoulder Press
202               3  Seated Shoulder Press
203               4  Seated Shoulder Press
204               5  Seated Shoulder Press
205               1                V-raise

[206 rows x 2 columns]

In [7]:
df.size

412

In [8]:
import os
from os import path
import shutil

In [9]:
#이미지 명 포멧 설정 : 운동 명 + 운동 순서(숫자)
copy_list = []
for i in range(df['IMG_NAME'].size) :
   copy_list.append(f"{df.iloc[i]['IMG_NAME']}-{df.iloc[i]['TRAINING_INDEX']}")

In [10]:
#추출(선별)된 이미지 이동/복사
for i in copy_list : 
    shutil.copy('img2/ia/'+i+'.jpg', 'copy_img/'+i+'.jpg')

In [14]:
file_list = os.listdir('copy_img')
index = []
training_name = []
training_index = []

#필요 운동 정보의 이미지에 대한 정보를 추출 및 복사
for i in range(len(file_list)) :
    training_index.append(file_list[i][file_list[i].find('-',len(file_list[i])-7)+1:].split('.')[0])
    training_name.append(file_list[i][:file_list[i].find('-',len(file_list[i])-7)])
    index.append(i+1)


file = pd.DataFrame({'index':index,'training_name':training_name,'training_index':training_index})
display(file)

     index                           training_name training_index
0        1                              Back Squat              1
1        2                              Back Squat              2
2        3                         Barbell Jammers              1
3        4                         Barbell Jammers              2
4        5                         Barbell Jammers              3
..     ...                                     ...            ...
201    202  Wrist Supination & Pronation Exercises              1
202    203  Wrist Supination & Pronation Exercises              2
203    204  Wrist Supination & Pronation Exercises              3
204    205  Wrist Supination & Pronation Exercises              4
205    206  Wrist Supination & Pronation Exercises              5

[206 rows x 3 columns]